export interface CalculatorField {
  name: string;
  label: string;
  unit?: string;
  placeholder?: string;
  defaultValue?: number;
  type?: "number" | "select";
  options?: { label: string; value: string | number }[];
  helperText?: string;
}

export interface CalculatorResult {
  label: string;
  unit: string;
  key: string;
}

export interface FAQ {
  question: string;
  answer: string;
}

export interface CalculatorConfig {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  metaDescription: string;
  intro: string;
  fields: CalculatorField[];
  results: CalculatorResult[];
  formula: string;
  howToUse: string[];
  howItWorks: string;
  faqs: FAQ[];
  relatedSlugs: string[];
  category: "concrete-masonry" | "landscaping" | "roofing" | "framing-structure" | "interior" | "outdoor";
}

export const categoryLabels: Record<string, string> = {
  "concrete-masonry": "Concrete & Masonry",
  landscaping: "Landscaping",
  roofing: "Roofing",
  "framing-structure": "Framing & Structure",
  interior: "Interior",
  outdoor: "Outdoor & Fencing",
};

export const calculators: CalculatorConfig[] = [
  {
    slug: "concrete-calculator",
    title: "Concrete Calculator",
    shortTitle: "Concrete",
    description: "Calculate how much concrete you need for slabs, footings, columns, and more.",
    metaDescription: "Free concrete calculator — estimate cubic yards, bags, and cost for slabs, footings, walls, and columns. Enter dimensions and get instant results.",
    intro: "Whether you're pouring a patio slab, setting fence post footings, or building a foundation wall, knowing exactly how much concrete to order saves money and prevents waste. Enter your project dimensions below to get an instant estimate in cubic yards and pre-mixed bags.",
    fields: [
      { name: "length", label: "Length", unit: "feet", placeholder: "10" },
      { name: "width", label: "Width", unit: "feet", placeholder: "10" },
      { name: "depth", label: "Depth / Thickness", unit: "inches", placeholder: "4" },
      { name: "pricePerYard", label: "Price per Cubic Yard (optional)", unit: "$", placeholder: "125", defaultValue: 125 },
    ],
    results: [
      { label: "Volume", unit: "cubic yards", key: "cubicYards" },
      { label: "Volume", unit: "cubic feet", key: "cubicFeet" },
      { label: "40 lb bags needed", unit: "bags", key: "bags40" },
      { label: "60 lb bags needed", unit: "bags", key: "bags60" },
      { label: "80 lb bags needed", unit: "bags", key: "bags80" },
      { label: "Estimated Cost", unit: "$", key: "cost" },
    ],
    formula: "Volume (cubic feet) = Length (ft) × Width (ft) × Depth (in) ÷ 12. Then divide by 27 to convert to cubic yards. A 40 lb bag covers ~0.011 yd³, a 60 lb bag covers ~0.017 yd³, and an 80 lb bag covers ~0.022 yd³. Always add 5–10% extra for waste.",
    howToUse: [
      "Measure the length and width of your project area in feet.",
      "Measure the depth or thickness in inches.",
      "Enter the values above and review the results.",
      "Optionally enter a price per cubic yard to see estimated material cost.",
      "Add 5–10% to the result for waste and spillage.",
    ],
    howItWorks: "This calculator converts your length, width, and depth measurements into cubic feet, then divides by 27 to get cubic yards — the standard unit concrete suppliers use. It also estimates the number of pre-mixed bags you would need if mixing by hand. The bag estimates use industry-standard yields: a 40 lb bag yields about 0.30 cubic feet, a 60 lb bag about 0.45 cubic feet, and an 80 lb bag about 0.60 cubic feet of cured concrete. For ready-mix delivery, most suppliers have a minimum order (often 1 yard) and charge extra for short loads under 5-10 yards.",
    faqs: [
      { question: "How many bags of concrete do I need for a 10×10 slab?", answer: "A 10×10 foot slab at 4 inches thick requires about 1.24 cubic yards of concrete. That's approximately 56 bags of 80 lb concrete mix, 67 bags of 60 lb mix, or 112 bags of 40 lb mix. For a project this size, ordering ready-mix delivery is usually more cost-effective than buying bags." },
      { question: "How much does a yard of concrete cost?", answer: "Ready-mix concrete typically costs $100–$200 per cubic yard depending on your location, the mix strength, and delivery distance. Short load fees (for orders under 5–10 yards) can add $50–$100. Pre-mixed bags cost more per yard but are practical for small projects." },
      { question: "How thick should a concrete slab be?", answer: "Standard residential slabs (patios, walkways) are 4 inches thick. Driveways should be at least 5–6 inches. Garage floors typically need 6 inches. For heavy loads, increase thickness and add rebar or wire mesh reinforcement." },
      { question: "How much extra concrete should I order?", answer: "Order 5–10% more than your calculated amount. Concrete is difficult to match if you run short mid-pour, and the cost of a little extra is far less than the hassle of a second delivery or batch." },
      { question: "What is the difference between concrete and cement?", answer: "Cement is one ingredient in concrete. Concrete is the finished product made from cement, water, sand, and gravel (aggregate). When people say 'cement mixer' or 'cement slab,' they usually mean concrete." },
    ],
    relatedSlugs: ["rebar-calculator", "brick-calculator", "gravel-calculator", "paver-calculator"],
    category: "concrete-masonry",
  },
  {
    slug: "mulch-calculator",
    title: "Mulch Calculator",
    shortTitle: "Mulch",
    description: "Calculate how many cubic yards or bags of mulch you need for your garden beds.",
    metaDescription: "Free mulch calculator — estimate cubic yards, bags, and cost for garden beds, flower beds, and landscaping. Enter area and depth for instant results.",
    intro: "Mulch helps retain soil moisture, suppress weeds, and give your landscaping a polished look. Use this calculator to figure out exactly how many cubic yards or bags of mulch you need for any bed or area.",
    fields: [
      { name: "length", label: "Length", unit: "feet", placeholder: "20" },
      { name: "width", label: "Width", unit: "feet", placeholder: "10" },
      { name: "depth", label: "Depth", unit: "inches", placeholder: "3" },
      { name: "pricePerYard", label: "Price per Cubic Yard (optional)", unit: "$", placeholder: "35", defaultValue: 35 },
    ],
    results: [
      { label: "Volume", unit: "cubic yards", key: "cubicYards" },
      { label: "Volume", unit: "cubic feet", key: "cubicFeet" },
      { label: "2 cu ft bags needed", unit: "bags", key: "bags2cf" },
      { label: "Estimated Cost (bulk)", unit: "$", key: "cost" },
    ],
    formula: "Volume (cubic feet) = Length (ft) × Width (ft) × Depth (in) ÷ 12. Divide by 27 for cubic yards. A standard bag of mulch is 2 cubic feet.",
    howToUse: [
      "Measure the length and width of your bed or area in feet.",
      "Decide on mulch depth — 2–3 inches is standard, 4 inches for weed suppression.",
      "Enter the values and review the results.",
      "Optionally enter bulk price per yard to estimate cost.",
    ],
    howItWorks: "The calculator multiplies your area dimensions by the depth (converted to feet) to get total cubic feet, then converts to cubic yards. Mulch is sold either in bulk (by the cubic yard) or in bags (typically 2 cubic feet each). Bulk is cheaper for larger areas — a cubic yard covers about 162 square feet at 2 inches deep, or 108 square feet at 3 inches deep.",
    faqs: [
      { question: "How deep should mulch be?", answer: "2–3 inches is the standard depth for most garden beds and around trees. For heavy weed suppression, go up to 4 inches. Avoid piling mulch deeper than 4 inches as it can prevent water from reaching plant roots and cause root rot." },
      { question: "How much area does a yard of mulch cover?", answer: "One cubic yard of mulch covers approximately 162 sq ft at 2 inches deep, 108 sq ft at 3 inches deep, or 81 sq ft at 4 inches deep." },
      { question: "How many bags of mulch are in a cubic yard?", answer: "A cubic yard equals 27 cubic feet. Standard bags are 2 cubic feet, so you need about 13.5 bags (round up to 14) to equal one cubic yard." },
      { question: "Is bulk or bagged mulch cheaper?", answer: "Bulk mulch is almost always cheaper per yard, typically $25–$50 per cubic yard delivered. Bagged mulch at $3–$5 per 2 cu ft bag works out to $40–$67 per cubic yard. Bulk makes sense for anything over 2–3 cubic yards." },
    ],
    relatedSlugs: ["gravel-calculator", "topsoil-calculator", "sod-calculator", "sand-calculator"],
    category: "landscaping",
  },
  {
    slug: "gravel-calculator",
    title: "Gravel Calculator",
    shortTitle: "Gravel",
    description: "Calculate how much gravel you need in tons and cubic yards for driveways, paths, and landscaping.",
    metaDescription: "Free gravel calculator — estimate tons, cubic yards, and cost for driveways, paths, and landscaping projects. Enter dimensions for instant results.",
    intro: "Gravel is used for driveways, pathways, drainage, and landscaping. Because it's sold by both weight (tons) and volume (cubic yards), it can be confusing to estimate. This calculator handles the conversion for you.",
    fields: [
      { name: "length", label: "Length", unit: "feet", placeholder: "20" },
      { name: "width", label: "Width", unit: "feet", placeholder: "10" },
      { name: "depth", label: "Depth", unit: "inches", placeholder: "4" },
      { name: "pricePerTon", label: "Price per Ton (optional)", unit: "$", placeholder: "50", defaultValue: 50 },
    ],
    results: [
      { label: "Volume", unit: "cubic yards", key: "cubicYards" },
      { label: "Volume", unit: "cubic feet", key: "cubicFeet" },
      { label: "Weight (approx)", unit: "tons", key: "tons" },
      { label: "Estimated Cost", unit: "$", key: "cost" },
    ],
    formula: "Volume (cubic feet) = Length × Width × Depth(in)/12. Divide by 27 for cubic yards. Gravel weighs approximately 2,800 lbs (1.4 tons) per cubic yard. Multiply cubic yards × 1.4 for tons.",
    howToUse: [
      "Measure the length and width of your area in feet.",
      "Determine the depth of gravel needed in inches.",
      "Enter the values and review volume and weight estimates.",
      "Optionally enter price per ton for cost estimate.",
    ],
    howItWorks: "This calculator computes volume from your dimensions, then estimates weight using the average density of gravel (approximately 2,800 lbs per cubic yard). Actual weight varies by gravel type — pea gravel is lighter (~2,500 lbs/yd³), crushed limestone is heavier (~2,700–3,000 lbs/yd³). For driveways, a depth of 4–6 inches is recommended with a compacted base layer.",
    faqs: [
      { question: "How deep should a gravel driveway be?", answer: "A gravel driveway should be 4–6 inches deep after compaction. For heavy vehicle traffic, use 6–8 inches with multiple layers: a base layer of larger stone (#3 or #57) topped with a finer surface layer (like #411 or crusher run)." },
      { question: "How many tons of gravel do I need for a driveway?", answer: "A typical single-car driveway (12×50 feet) at 4 inches deep needs about 3.3 cubic yards or roughly 4.6 tons of gravel. A two-car driveway (24×50 feet) at the same depth needs about 6.6 cubic yards or 9.3 tons." },
      { question: "How much does a ton of gravel cover?", answer: "One ton of gravel covers approximately 80-100 square feet at 2 inches deep, 50-60 square feet at 3 inches deep, or 40-50 square feet at 4 inches deep, depending on the type of gravel." },
      { question: "What is the cheapest gravel for a driveway?", answer: "Crushed stone or 'crusher run' is typically the most affordable at $20–$40 per ton. Pea gravel runs $25–$50 per ton. Decorative gravels like river rock or marble chips are the most expensive at $50–$150+ per ton." },
    ],
    relatedSlugs: ["concrete-calculator", "sand-calculator", "mulch-calculator", "paver-calculator"],
    category: "landscaping",
  },
  {
    slug: "paint-calculator",
    title: "Paint Calculator",
    shortTitle: "Paint",
    description: "Calculate how many gallons of paint you need for walls, ceilings, and rooms.",
    metaDescription: "Free paint calculator — estimate gallons needed for any room, wall, or project. Accounts for doors, windows, and multiple coats.",
    intro: "Buying the right amount of paint saves trips to the store and money. This calculator estimates gallons needed based on your room dimensions, accounting for doors and windows you won't be painting.",
    fields: [
      { name: "roomLength", label: "Room Length", unit: "feet", placeholder: "15" },
      { name: "roomWidth", label: "Room Width", unit: "feet", placeholder: "12" },
      { name: "wallHeight", label: "Wall Height", unit: "feet", placeholder: "8" },
      { name: "doors", label: "Number of Doors", unit: "", placeholder: "2", defaultValue: 2 },
      { name: "windows", label: "Number of Windows", unit: "", placeholder: "2", defaultValue: 2 },
      { name: "coats", label: "Number of Coats", unit: "", placeholder: "2", defaultValue: 2 },
    ],
    results: [
      { label: "Total Wall Area", unit: "sq ft", key: "wallArea" },
      { label: "Paintable Area", unit: "sq ft", key: "paintableArea" },
      { label: "Gallons Needed", unit: "gallons", key: "gallons" },
    ],
    formula: "Wall area = 2 × (Length + Width) × Height. Subtract ~21 sq ft per door and ~15 sq ft per window. Divide paintable area by 350 sq ft/gallon coverage, then multiply by number of coats.",
    howToUse: [
      "Measure the room length and width in feet.",
      "Measure the wall height (usually 8 or 9 feet).",
      "Count the number of standard doors and windows.",
      "Select number of coats (2 is recommended for most jobs).",
      "Review the gallons needed.",
    ],
    howItWorks: "One gallon of paint covers approximately 350–400 square feet of smooth wall with one coat. This calculator uses 350 sq ft as a conservative estimate. It subtracts 21 square feet per standard door (3×7 ft) and 15 square feet per average window (3×5 ft) from the total wall area. Textured walls, dark-to-light color changes, and bare drywall may require an extra coat.",
    faqs: [
      { question: "How many gallons of paint for a 12×12 room?", answer: "A 12×12 room with 8-foot ceilings, 2 doors, and 2 windows needs about 2 gallons for 2 coats. This covers approximately 312 square feet of paintable wall area." },
      { question: "How much does a gallon of paint cover?", answer: "One gallon of interior paint covers 350–400 square feet on smooth surfaces with one coat. Rough or textured surfaces may only get 300 square feet per gallon." },
      { question: "Do I really need two coats of paint?", answer: "In most cases, yes. Two coats provide even coverage, true color, better durability, and hide the previous color. You might get away with one coat if you're painting the same color or using a high-quality paint-and-primer combo over a light-colored wall." },
      { question: "Should I buy extra paint?", answer: "Yes, buy about 10% more than calculated. You'll want extra for touch-ups, and paint colors can vary slightly between batches. Most stores accept returns on unopened cans." },
    ],
    relatedSlugs: ["drywall-calculator", "flooring-calculator", "tile-calculator"],
    category: "interior",
  },
  {
    slug: "roofing-calculator",
    title: "Roofing Calculator",
    shortTitle: "Roofing",
    description: "Calculate roofing squares, bundles of shingles, and materials needed for your roof.",
    metaDescription: "Free roofing calculator — estimate squares, shingle bundles, underlayment, and nails needed. Enter roof dimensions and pitch for instant results.",
    intro: "Roofing materials are sold by the 'square' — a unit equal to 100 square feet. This calculator takes your roof dimensions and pitch to estimate materials including shingle bundles, underlayment, and ridge cap.",
    fields: [
      { name: "length", label: "Roof Length", unit: "feet", placeholder: "40" },
      { name: "width", label: "Roof Width (eave to ridge)", unit: "feet", placeholder: "20" },
      { name: "pitch", label: "Roof Pitch", unit: "/12", placeholder: "6", defaultValue: 6 },
      { name: "wastePercent", label: "Waste Factor", unit: "%", placeholder: "10", defaultValue: 10 },
    ],
    results: [
      { label: "Flat Area", unit: "sq ft", key: "flatArea" },
      { label: "Actual Roof Area", unit: "sq ft", key: "roofArea" },
      { label: "Roofing Squares", unit: "squares", key: "squares" },
      { label: "Shingle Bundles (3-tab)", unit: "bundles", key: "bundles" },
      { label: "Underlayment Rolls", unit: "rolls", key: "underlayment" },
    ],
    formula: "Flat area = Length × Width. Pitch multiplier = √(1 + (pitch/12)²). Actual area = Flat area × Pitch multiplier × 2 (for both sides of a gable roof). Squares = Actual area ÷ 100. Bundles = Squares × 3. Add waste factor.",
    howToUse: [
      "Measure the length of your roof (ridge line) in feet.",
      "Measure the width from eave to ridge on one side.",
      "Enter the roof pitch (rise per 12 inches of run).",
      "Adjust the waste percentage if needed (10% is standard).",
      "Review squares and bundle estimates.",
    ],
    howItWorks: "Roof pitch affects actual surface area — a steeper roof has more area than the flat footprint suggests. This calculator uses a pitch multiplier derived from the Pythagorean theorem to convert flat area to actual roof area. It assumes a simple gable (two-sided) roof. Complex roofs with hips, valleys, and dormers require additional material — increase the waste factor to 15–20% for these. Three bundles of standard 3-tab shingles equal one square (100 sq ft).",
    faqs: [
      { question: "What is a roofing square?", answer: "A roofing square is a unit of measurement equal to 100 square feet of roof area. Roofing materials including shingles, underlayment, and flashing are all priced and sold by the square." },
      { question: "How many bundles of shingles per square?", answer: "Standard 3-tab shingles come 3 bundles per square (100 sq ft). Architectural/dimensional shingles vary — some are 3 bundles per square, heavier ones may be 4–5 bundles per square. Check the manufacturer's specs." },
      { question: "How do I measure roof pitch?", answer: "From inside the attic, place a level horizontally against a rafter. Measure 12 inches along the level, then measure the vertical distance from that 12-inch mark up to the rafter. That vertical distance is the pitch (e.g., 6 inches = 6/12 pitch)." },
      { question: "How much does a new roof cost?", answer: "Asphalt shingle roofs typically cost $5,000–$12,000 for a standard home (1,500–2,500 sq ft roof area), or roughly $3–$5 per square foot installed. Metal roofing runs $8–$14 per square foot. Prices vary significantly by region and roof complexity." },
    ],
    relatedSlugs: ["roof-pitch-calculator", "lumber-calculator", "insulation-calculator"],
    category: "roofing",
  },
  {
    slug: "tile-calculator",
    title: "Tile Calculator",
    shortTitle: "Tile",
    description: "Calculate how many tiles you need for floors, walls, and backsplashes.",
    metaDescription: "Free tile calculator — estimate tiles needed, boxes to buy, and account for waste. Enter room and tile dimensions for instant results.",
    intro: "Getting the tile count right avoids expensive re-orders (tiles from different production lots can vary in color). Enter your project area and tile size to get an accurate estimate with waste factored in.",
    fields: [
      { name: "areaLength", label: "Area Length", unit: "feet", placeholder: "12" },
      { name: "areaWidth", label: "Area Width", unit: "feet", placeholder: "10" },
      { name: "tileLength", label: "Tile Length", unit: "inches", placeholder: "12" },
      { name: "tileWidth", label: "Tile Width", unit: "inches", placeholder: "12" },
      { name: "tilesPerBox", label: "Tiles per Box", unit: "", placeholder: "10", defaultValue: 10 },
      { name: "wastePercent", label: "Waste Factor", unit: "%", placeholder: "10", defaultValue: 10 },
    ],
    results: [
      { label: "Total Area", unit: "sq ft", key: "totalArea" },
      { label: "Tiles Needed", unit: "tiles", key: "tilesNeeded" },
      { label: "Boxes to Buy", unit: "boxes", key: "boxes" },
    ],
    formula: "Area = Length × Width. Tile area = Tile Length (in) × Tile Width (in) ÷ 144 to convert to sq ft. Tiles needed = (Area ÷ Tile area) × (1 + waste%). Boxes = ceil(Tiles ÷ Tiles per box).",
    howToUse: [
      "Measure the area to be tiled in feet (length × width).",
      "Enter the tile dimensions in inches.",
      "Enter how many tiles come per box (check the box label).",
      "Adjust waste factor — 10% for simple layouts, 15% for diagonal patterns.",
      "Review tiles and boxes needed.",
    ],
    howItWorks: "This calculator divides your total project area by the area of a single tile to determine how many tiles you need, then adds a waste factor for cuts, breakage, and pattern matching. Diagonal (45°) installations waste more material than straight layouts because edge cuts produce smaller usable pieces. Always buy all your tile at once from the same production lot — tiles from different lots may have slight color variations that are visible once installed.",
    faqs: [
      { question: "How much extra tile should I buy?", answer: "Buy 10% extra for standard straight layouts, 15% for diagonal patterns, and 20% for complex mosaic patterns or rooms with many corners and obstacles. Always keep a few spare tiles for future repairs." },
      { question: "How many 12×12 tiles for 100 sq ft?", answer: "You need 100 tiles for the area itself, plus waste. At 10% waste, buy 110 tiles. If they come 10 per box, that's 11 boxes." },
      { question: "What size tile is best for small rooms?", answer: "Larger tiles (12×24 or 18×18) can actually make small rooms look bigger because there are fewer grout lines. However, very large tiles may require more cuts in a small space. 12×12 is a versatile middle ground." },
      { question: "Do I need to account for grout lines?", answer: "For most residential tile jobs with standard 1/8 to 1/4 inch grout lines, the waste factor covers the grout line area. For wide grout lines (3/8 inch+), you can reduce tile count by about 5%." },
    ],
    relatedSlugs: ["flooring-calculator", "paint-calculator", "gravel-calculator"],
    category: "interior",
  },
  {
    slug: "lumber-calculator",
    title: "Lumber & Board Foot Calculator",
    shortTitle: "Lumber",
    description: "Calculate board feet, total cost, and quantity for lumber and framing projects.",
    metaDescription: "Free lumber and board foot calculator — convert dimensions to board feet, estimate cost, and plan your lumber order. Instant results.",
    intro: "Hardwood lumber is sold by the board foot — a unit that can be confusing. This calculator converts standard dimensions to board feet and estimates your total cost.",
    fields: [
      { name: "thickness", label: "Thickness", unit: "inches", placeholder: "1" },
      { name: "width", label: "Width", unit: "inches", placeholder: "6" },
      { name: "length", label: "Length", unit: "feet", placeholder: "8" },
      { name: "quantity", label: "Number of Boards", unit: "", placeholder: "10", defaultValue: 1 },
      { name: "pricePerBF", label: "Price per Board Foot (optional)", unit: "$", placeholder: "5", defaultValue: 5 },
    ],
    results: [
      { label: "Board Feet (per board)", unit: "BF", key: "boardFeetEach" },
      { label: "Total Board Feet", unit: "BF", key: "totalBoardFeet" },
      { label: "Estimated Cost", unit: "$", key: "cost" },
    ],
    formula: "Board Feet = Thickness (in) × Width (in) × Length (ft) ÷ 12. Total = Board Feet per board × Quantity.",
    howToUse: [
      "Enter the board thickness in inches (nominal or actual).",
      "Enter the board width in inches.",
      "Enter the board length in feet.",
      "Enter the number of boards you need.",
      "Optionally enter price per board foot for cost estimate.",
    ],
    howItWorks: "A board foot is a volume measurement: 1 inch thick × 12 inches wide × 12 inches long (144 cubic inches). Hardwood lumber is priced by the board foot, while dimensional lumber (2×4s, 2×6s) is typically priced per linear foot or per piece. Note that nominal dimensions differ from actual — a '2×4' is actually 1.5×3.5 inches. This calculator uses the values you enter directly, so use actual dimensions for accurate results.",
    faqs: [
      { question: "What is a board foot?", answer: "A board foot (BF) is a unit of volume equal to 144 cubic inches — think of a board that is 1 inch thick, 12 inches wide, and 12 inches long. It's the standard pricing unit for hardwood lumber." },
      { question: "How do I convert nominal to actual lumber dimensions?", answer: "Common conversions: 1× = 3/4 inch actual, 2× = 1.5 inches actual. Width: 4 = 3.5, 6 = 5.5, 8 = 7.25, 10 = 9.25, 12 = 11.25. For example, a 2×6 is actually 1.5 × 5.5 inches." },
      { question: "How much does lumber cost per board foot?", answer: "Prices vary widely by species. Pine/poplar: $2–$5/BF. Oak: $4–$8/BF. Walnut: $8–$15/BF. Cherry/Maple: $5–$10/BF. Exotic hardwoods: $10–$30+/BF. Prices fluctuate with market conditions." },
    ],
    relatedSlugs: ["deck-calculator", "fence-calculator", "stair-calculator", "drywall-calculator"],
    category: "framing-structure",
  },
  {
    slug: "drywall-calculator",
    title: "Drywall Calculator",
    shortTitle: "Drywall",
    description: "Calculate the number of drywall sheets, joint compound, and tape needed.",
    metaDescription: "Free drywall calculator — estimate sheets, joint compound, and tape for any room. Enter dimensions and get an instant material list.",
    intro: "Whether you're finishing a basement, remodeling a room, or repairing water damage, this calculator tells you exactly how many sheets of drywall to buy plus the joint compound and tape to finish the job.",
    fields: [
      { name: "roomLength", label: "Room Length", unit: "feet", placeholder: "15" },
      { name: "roomWidth", label: "Room Width", unit: "feet", placeholder: "12" },
      { name: "wallHeight", label: "Wall Height", unit: "feet", placeholder: "8" },
      { name: "doCeiling", label: "Include Ceiling?", type: "select", options: [{ label: "Yes", value: 1 }, { label: "No", value: 0 }] },
      { name: "sheetSize", label: "Sheet Size", type: "select", options: [{ label: "4×8 (32 sq ft)", value: 32 }, { label: "4×12 (48 sq ft)", value: 48 }] },
    ],
    results: [
      { label: "Wall Area", unit: "sq ft", key: "wallArea" },
      { label: "Ceiling Area", unit: "sq ft", key: "ceilingArea" },
      { label: "Total Area", unit: "sq ft", key: "totalArea" },
      { label: "Sheets Needed", unit: "sheets", key: "sheets" },
      { label: "Joint Compound", unit: "gallons", key: "compound" },
      { label: "Tape", unit: "feet", key: "tape" },
    ],
    formula: "Wall area = 2 × (Length + Width) × Height. Ceiling area = Length × Width (if included). Sheets = ceil(Total area ÷ Sheet size × 1.10 for waste). Joint compound ≈ 0.053 gallons per sq ft. Tape ≈ 1 foot per sq ft of drywall.",
    howToUse: [
      "Enter room length and width in feet.",
      "Enter wall height (usually 8 or 9 feet).",
      "Choose whether to include the ceiling.",
      "Select your drywall sheet size.",
      "Review the material estimates.",
    ],
    howItWorks: "This calculator computes total wall area (and ceiling if selected), adds 10% for waste and cuts, then divides by the sheet size to get the number of sheets. Joint compound and tape estimates follow industry rules of thumb. For rooms with many doors and windows, you may need slightly less, but it's better to have extra than run short mid-job.",
    faqs: [
      { question: "What thickness drywall should I use?", answer: "1/2 inch is standard for walls. 5/8 inch is required on ceilings (it resists sagging) and on walls/ceilings in attached garages (fire code). 1/4 inch is used for curved surfaces. Moisture-resistant (green board) or mold-resistant (purple board) is recommended for bathrooms." },
      { question: "How many sheets of drywall for a 12×12 room?", answer: "A 12×12 room with 8-foot ceilings needs about 12 sheets of 4×8 drywall for the walls, plus 5–6 sheets for the ceiling. With 10% waste, plan on 18–20 sheets total." },
      { question: "Should I use 4×8 or 4×12 drywall?", answer: "4×12 sheets mean fewer seams on longer walls, which reduces taping and finishing work. They're harder to handle — you'll likely need a helper. 4×8 is easier for DIY. Use 4×12 if you can manage the weight." },
    ],
    relatedSlugs: ["paint-calculator", "insulation-calculator", "lumber-calculator"],
    category: "interior",
  },
  {
    slug: "deck-calculator",
    title: "Deck Calculator",
    shortTitle: "Deck",
    description: "Calculate decking boards, joists, posts, and materials for your deck project.",
    metaDescription: "Free deck calculator — estimate decking boards, joists, posts, and total cost. Enter your deck dimensions for a complete material list.",
    intro: "Planning a deck? This calculator estimates the decking boards, joists, and support posts you'll need based on your deck dimensions. It covers standard residential deck construction with 16-inch joist spacing.",
    fields: [
      { name: "deckLength", label: "Deck Length", unit: "feet", placeholder: "16" },
      { name: "deckWidth", label: "Deck Width", unit: "feet", placeholder: "12" },
      { name: "boardWidth", label: "Deck Board Width", unit: "inches", placeholder: "5.5", defaultValue: 5.5 },
      { name: "boardLength", label: "Deck Board Length", unit: "feet", placeholder: "16", defaultValue: 16 },
    ],
    results: [
      { label: "Deck Area", unit: "sq ft", key: "deckArea" },
      { label: "Decking Boards", unit: "boards", key: "deckingBoards" },
      { label: "Joists (16\" OC)", unit: "joists", key: "joists" },
      { label: "Support Posts (8' OC)", unit: "posts", key: "posts" },
      { label: "Joist Hangers", unit: "hangers", key: "hangers" },
    ],
    formula: "Deck area = Length × Width. Decking boards = (Width ÷ Board Width in feet) × (Length ÷ Board Length), rounded up, +10% waste. Joists = (Length ÷ 1.33) + 1 for 16\" spacing. Posts = based on 8-foot max spacing per code.",
    howToUse: [
      "Enter the overall deck length and width in feet.",
      "Enter the width of your deck boards in inches (5.5\" is standard for 2×6 or composite).",
      "Enter the length of deck boards you plan to buy.",
      "Review the material list.",
    ],
    howItWorks: "This calculator uses standard residential deck construction practices. Joists are spaced 16 inches on center, which is code for most deck boards. Support posts are calculated at 8-foot maximum spacing per IRC code requirements. The calculator adds 10% waste for decking boards to account for cuts and defects. For composite decking, the board width is typically 5.5 inches; for 2×6 lumber, actual width is also 5.5 inches.",
    faqs: [
      { question: "How many deck boards for a 12×16 deck?", answer: "A 12×16 foot deck using 5.5-inch wide boards (standard 2×6 or composite) needs approximately 28 boards if using 16-foot lengths with about 10% extra for waste, totaling around 31 boards." },
      { question: "Wood or composite decking?", answer: "Pressure-treated wood costs $2–$4 per linear foot but needs annual maintenance. Composite costs $4–$10 per linear foot but is virtually maintenance-free and lasts 25+ years. Composite pays for itself in about 7–10 years when you factor in stain, seal, and replacement costs." },
      { question: "How far apart should deck joists be?", answer: "16 inches on center is standard and required by most building codes. Some composite decking manufacturers require 12-inch spacing — check your product specifications." },
    ],
    relatedSlugs: ["lumber-calculator", "stair-calculator", "fence-calculator", "concrete-calculator"],
    category: "outdoor",
  },
  {
    slug: "fence-calculator",
    title: "Fence Calculator",
    shortTitle: "Fence",
    description: "Calculate posts, rails, pickets, and materials for wood and vinyl fences.",
    metaDescription: "Free fence calculator — estimate posts, rails, pickets, concrete, and cost for wood or vinyl fences. Enter fence length and height for instant results.",
    intro: "Building a fence? This calculator estimates the posts, rails, and pickets you need based on your total fence length and desired height. It uses standard 8-foot post spacing.",
    fields: [
      { name: "totalLength", label: "Total Fence Length", unit: "feet", placeholder: "100" },
      { name: "fenceHeight", label: "Fence Height", unit: "feet", placeholder: "6", defaultValue: 6 },
      { name: "picketWidth", label: "Picket Width", unit: "inches", placeholder: "3.5", defaultValue: 3.5 },
      { name: "picketGap", label: "Gap Between Pickets", unit: "inches", placeholder: "0", defaultValue: 0 },
    ],
    results: [
      { label: "Posts (8' spacing)", unit: "posts", key: "posts" },
      { label: "Rails (2 per section)", unit: "rails", key: "rails" },
      { label: "Pickets", unit: "pickets", key: "pickets" },
      { label: "Concrete (per post)", unit: "bags (50lb)", key: "concreteBags" },
      { label: "Total Concrete", unit: "bags", key: "totalConcrete" },
    ],
    formula: "Posts = (Total Length ÷ 8) + 1. Rails = (Posts - 1) × 2 (for 2 horizontal rails). Use 3 rails for fences over 6 feet. Pickets = Total Length ÷ (Picket Width + Gap) in feet.",
    howToUse: [
      "Measure the total length of fence needed in feet.",
      "Choose fence height (4, 6, or 8 feet are standard).",
      "Enter picket width — 3.5 inches is standard for a 1×4 or dog-ear picket.",
      "Enter gap between pickets (0 for a privacy fence).",
      "Review the material estimates.",
    ],
    howItWorks: "Fence posts are typically set 8 feet apart (6 feet for vinyl or windy areas). Each section between posts gets 2 horizontal rails (3 rails for fences over 6 feet). Pickets span the full length. Posts should be buried at least 1/3 of the total height (a 6-foot fence needs posts set 2 feet deep, so buy 8-foot posts). Each post hole typically needs one 50-lb bag of fast-setting concrete.",
    faqs: [
      { question: "How deep should fence posts be?", answer: "Bury fence posts at least 1/3 of the above-ground height, plus 6 inches. For a 6-foot fence, dig holes 30 inches deep. In areas with frost, posts should extend below the frost line — check your local code." },
      { question: "How much does a wood fence cost per foot?", answer: "A basic 6-foot privacy fence costs $15–$30 per linear foot for materials, or $25–$50 per foot installed. Cedar costs more than pressure-treated pine but lasts longer without treatment." },
      { question: "How far apart should fence posts be?", answer: "8 feet is standard for wood fences. Vinyl fences typically use 6-foot spacing. In areas with high winds, reduce spacing to 6 feet for wood as well. Always set corner and gate posts first." },
    ],
    relatedSlugs: ["concrete-calculator", "deck-calculator", "lumber-calculator", "paver-calculator"],
    category: "outdoor",
  },
  {
    slug: "flooring-calculator",
    title: "Flooring Calculator",
    shortTitle: "Flooring",
    description: "Calculate how much flooring material you need — hardwood, laminate, vinyl, or LVP.",
    metaDescription: "Free flooring calculator — estimate square footage, boxes, and cost for hardwood, laminate, vinyl plank, or LVP flooring. Instant results.",
    intro: "Whether you're installing hardwood, laminate, vinyl plank, or LVP, you need to know exactly how much to order. This calculator accounts for waste from cuts and gives you box counts based on your product's coverage.",
    fields: [
      { name: "roomLength", label: "Room Length", unit: "feet", placeholder: "15" },
      { name: "roomWidth", label: "Room Width", unit: "feet", placeholder: "12" },
      { name: "sqftPerBox", label: "Sq Ft per Box", unit: "sq ft", placeholder: "20", defaultValue: 20 },
      { name: "wastePercent", label: "Waste Factor", unit: "%", placeholder: "10", defaultValue: 10 },
      { name: "pricePerSqFt", label: "Price per Sq Ft (optional)", unit: "$", placeholder: "3", defaultValue: 3 },
    ],
    results: [
      { label: "Room Area", unit: "sq ft", key: "roomArea" },
      { label: "Total Needed (with waste)", unit: "sq ft", key: "totalNeeded" },
      { label: "Boxes to Buy", unit: "boxes", key: "boxes" },
      { label: "Estimated Material Cost", unit: "$", key: "cost" },
    ],
    formula: "Room area = Length × Width. Total needed = Room area × (1 + waste%). Boxes = ceil(Total needed ÷ Sq ft per box).",
    howToUse: [
      "Measure room length and width in feet.",
      "Check the flooring product box for square footage per box.",
      "Adjust waste factor — 10% standard, 15% for diagonal installation.",
      "Enter price per square foot if you want a cost estimate.",
    ],
    howItWorks: "This calculator multiplies your room dimensions to get square footage, adds a waste factor for cuts and fitting, then divides by the coverage per box to tell you how many boxes to buy. Always round up — you can't buy partial boxes. Keep 2–3 extra planks from the same batch for future repairs, as color matching across production runs is difficult.",
    faqs: [
      { question: "How much flooring waste should I plan for?", answer: "10% for standard straight installations, 15% for diagonal or herringbone patterns, 20% for rooms with lots of angles or obstacles. Hallways and small rooms waste more proportionally than large open spaces." },
      { question: "How much does flooring cost per square foot?", answer: "Vinyl plank/LVP: $1–$5/sq ft. Laminate: $1–$4/sq ft. Engineered hardwood: $3–$10/sq ft. Solid hardwood: $5–$15/sq ft. Add $2–$5/sq ft for professional installation." },
      { question: "Should I acclimate flooring before installation?", answer: "Yes. Leave flooring in the room where it will be installed for 48–72 hours before starting. This lets the material adjust to the room's temperature and humidity, preventing gaps or buckling after installation." },
    ],
    relatedSlugs: ["tile-calculator", "paint-calculator", "stair-calculator"],
    category: "interior",
  },
  {
    slug: "roof-pitch-calculator",
    title: "Roof Pitch Calculator",
    shortTitle: "Roof Pitch",
    description: "Calculate roof pitch, angle in degrees, and rise per foot from your measurements.",
    metaDescription: "Free roof pitch calculator — convert between pitch ratio, degrees, and percentage. Enter rise and run for instant results.",
    intro: "Roof pitch describes the steepness of a roof as a ratio of rise to run. This calculator converts between pitch ratios (like 6/12), angles in degrees, and slope percentages — useful for planning roofing, framing, or drainage projects.",
    fields: [
      { name: "rise", label: "Rise", unit: "inches", placeholder: "6" },
      { name: "run", label: "Run", unit: "inches", placeholder: "12", defaultValue: 12 },
    ],
    results: [
      { label: "Pitch", unit: "/12", key: "pitch" },
      { label: "Angle", unit: "degrees", key: "degrees" },
      { label: "Slope", unit: "%", key: "slopePercent" },
      { label: "Pitch Multiplier", unit: "×", key: "multiplier" },
    ],
    formula: "Pitch = Rise ÷ Run × 12 (expressed as X/12). Angle = arctan(Rise/Run) in degrees. Slope % = (Rise/Run) × 100. Pitch multiplier = √(1 + (Rise/Run)²).",
    howToUse: [
      "Measure the rise (vertical height) in inches over any convenient run.",
      "Measure the run (horizontal distance) in inches — default is 12 inches.",
      "Review the pitch, angle, and multiplier results.",
    ],
    howItWorks: "Roof pitch is expressed as a ratio — '6/12' means the roof rises 6 inches for every 12 inches of horizontal run. The pitch multiplier is used to convert flat (plan-view) measurements to actual roof surface area. For example, a 6/12 pitch has a multiplier of 1.118, meaning the actual roof surface is 11.8% larger than the flat footprint. This multiplier is essential for ordering materials.",
    faqs: [
      { question: "What is a common roof pitch?", answer: "Most residential roofs are between 4/12 and 9/12. The most common is 6/12 (about 26.5 degrees). Low-slope roofs are 2/12 or less. Steep roofs (9/12 and above) are common in areas with heavy snow." },
      { question: "What is the minimum pitch for shingles?", answer: "Standard asphalt shingles require a minimum pitch of 2/12. Below that, you need a low-slope roofing system like rolled roofing, built-up roofing, or a membrane system (TPO, EPDM)." },
      { question: "What pitch is a 45-degree roof?", answer: "A 45-degree angle equals a 12/12 pitch — the roof rises 12 inches for every 12 inches of run. This is considered a steep roof." },
    ],
    relatedSlugs: ["roofing-calculator", "stair-calculator", "lumber-calculator"],
    category: "roofing",
  },
  {
    slug: "sand-calculator",
    title: "Sand Calculator",
    shortTitle: "Sand",
    description: "Calculate how much sand you need in tons and cubic yards.",
    metaDescription: "Free sand calculator — estimate tons and cubic yards of sand for construction, landscaping, and paver base. Enter dimensions for instant results.",
    intro: "Sand is used for paver bases, leveling, play areas, and concrete mixing. This calculator estimates how much you need by volume and weight.",
    fields: [
      { name: "length", label: "Length", unit: "feet", placeholder: "20" },
      { name: "width", label: "Width", unit: "feet", placeholder: "10" },
      { name: "depth", label: "Depth", unit: "inches", placeholder: "2" },
      { name: "pricePerTon", label: "Price per Ton (optional)", unit: "$", placeholder: "30", defaultValue: 30 },
    ],
    results: [
      { label: "Volume", unit: "cubic yards", key: "cubicYards" },
      { label: "Volume", unit: "cubic feet", key: "cubicFeet" },
      { label: "Weight (approx)", unit: "tons", key: "tons" },
      { label: "Estimated Cost", unit: "$", key: "cost" },
    ],
    formula: "Volume (cu ft) = Length × Width × Depth(in)/12. Cubic yards = Volume ÷ 27. Sand weighs ~2,700 lbs (1.35 tons) per cubic yard. Tons = cubic yards × 1.35.",
    howToUse: [
      "Measure the area length and width in feet.",
      "Determine the sand depth in inches.",
      "Enter values and review results.",
      "Enter price per ton for cost estimate.",
    ],
    howItWorks: "The calculator computes volume from your dimensions and converts to both cubic yards and tons. Sand density varies by moisture content and type — dry sand is about 2,600 lbs/yd³, while wet sand can be 3,100+ lbs/yd³. This calculator uses 2,700 lbs/yd³ as a practical average. Always order 5–10% extra for compaction loss.",
    faqs: [
      { question: "How much does a cubic yard of sand weigh?", answer: "Approximately 2,500–2,800 lbs (1.25–1.4 tons) depending on moisture content and sand type. Wet sand is significantly heavier than dry sand." },
      { question: "How much sand do I need for pavers?", answer: "For a paver base, use 1 inch of bedding sand over your compacted gravel base. For a 100 sq ft patio, you need about 0.31 cubic yards (roughly 0.42 tons) of sand." },
      { question: "What type of sand should I use?", answer: "Concrete sand (coarse, washed) for mixing and paver bedding. Mason sand (fine) for mortar and play areas. Utility sand for backfill. Polymeric sand for filling paver joints." },
    ],
    relatedSlugs: ["gravel-calculator", "concrete-calculator", "paver-calculator", "mulch-calculator"],
    category: "landscaping",
  },
  {
    slug: "stair-calculator",
    title: "Stair Calculator",
    shortTitle: "Stairs",
    description: "Calculate stair rise, run, number of steps, and stringer length.",
    metaDescription: "Free stair calculator — calculate riser height, tread depth, number of steps, and stringer length. Enter total rise and run for code-compliant results.",
    intro: "Building stairs that are comfortable and code-compliant requires precise measurements. This calculator determines the number of steps, individual riser height, and stringer length from your total rise and desired run.",
    fields: [
      { name: "totalRise", label: "Total Rise (floor to floor)", unit: "inches", placeholder: "108" },
      { name: "treadDepth", label: "Tread Depth (run per step)", unit: "inches", placeholder: "10", defaultValue: 10 },
      { name: "riserHeight", label: "Desired Riser Height", unit: "inches", placeholder: "7.5", defaultValue: 7.5 },
    ],
    results: [
      { label: "Number of Risers", unit: "risers", key: "numRisers" },
      { label: "Actual Riser Height", unit: "inches", key: "actualRiser" },
      { label: "Number of Treads", unit: "treads", key: "numTreads" },
      { label: "Total Run", unit: "inches", key: "totalRun" },
      { label: "Stringer Length", unit: "inches", key: "stringerLength" },
    ],
    formula: "Risers = round(Total Rise ÷ Desired Riser Height). Actual riser = Total Rise ÷ Risers. Treads = Risers - 1. Total run = Treads × Tread Depth. Stringer = √(Total Rise² + Total Run²).",
    howToUse: [
      "Measure the total rise from the finished floor at the bottom to the finished floor at the top, in inches.",
      "Enter your desired tread depth (10 inches is standard).",
      "Enter your target riser height (7–7.75 inches meets most codes).",
      "Review the calculated dimensions.",
    ],
    howItWorks: "Building codes require consistent riser heights — all risers must be within 3/8 inch of each other. This calculator divides the total rise into equal risers as close to your target height as possible. The stringer length is the diagonal measurement needed to cut your stair stringers (typically 2×12 lumber). IRC residential code requires: maximum riser height of 7.75 inches, minimum tread depth of 10 inches, and minimum stair width of 36 inches.",
    faqs: [
      { question: "What is the ideal riser height?", answer: "7 to 7.5 inches is most comfortable. Code maximum is 7.75 inches (IRC). All risers in a flight must be within 3/8 inch of each other — consistency matters more than the exact height." },
      { question: "What is the 7-11 rule for stairs?", answer: "A common rule of thumb: risers should be about 7 inches and treads about 11 inches. More precisely, the sum of two risers plus one tread should equal 24–25 inches for comfort." },
      { question: "How long of a 2×12 do I need for stair stringers?", answer: "Use this calculator's stringer length result. For a standard 9-foot ceiling (about 108 inches total rise with floor thickness), you'll need approximately 12–14 foot 2×12s for stringers." },
    ],
    relatedSlugs: ["deck-calculator", "lumber-calculator", "concrete-calculator"],
    category: "framing-structure",
  },
  {
    slug: "brick-calculator",
    title: "Brick Calculator",
    shortTitle: "Brick",
    description: "Calculate how many bricks you need for walls, patios, and walkways.",
    metaDescription: "Free brick calculator — estimate bricks needed for walls, patios, walkways, and more. Accounts for mortar joints and waste.",
    intro: "Whether you're building a wall, patio, or walkway, this calculator estimates the number of bricks required based on your project dimensions and brick size.",
    fields: [
      { name: "wallLength", label: "Wall/Area Length", unit: "feet", placeholder: "20" },
      { name: "wallHeight", label: "Wall Height", unit: "feet", placeholder: "4" },
      { name: "brickLength", label: "Brick Length", unit: "inches", placeholder: "8", defaultValue: 8 },
      { name: "brickHeight", label: "Brick Height", unit: "inches", placeholder: "2.25", defaultValue: 2.25 },
      { name: "mortarJoint", label: "Mortar Joint Width", unit: "inches", placeholder: "0.375", defaultValue: 0.375 },
      { name: "wastePercent", label: "Waste Factor", unit: "%", placeholder: "10", defaultValue: 10 },
    ],
    results: [
      { label: "Wall Area", unit: "sq ft", key: "wallArea" },
      { label: "Bricks Needed", unit: "bricks", key: "bricksNeeded" },
      { label: "Mortar Bags (80 lb)", unit: "bags", key: "mortarBags" },
    ],
    formula: "Brick + mortar area = (Brick Length + Joint) × (Brick Height + Joint). Bricks per sq ft = 144 ÷ Brick area. Total = Wall area × Bricks per sq ft × (1 + waste%).",
    howToUse: [
      "Enter the length and height of the wall or area in feet.",
      "Enter brick dimensions (standard modular brick is 8 × 2.25 inches).",
      "Enter mortar joint width (standard is 3/8 inch).",
      "Adjust waste factor and review results.",
    ],
    howItWorks: "This calculator determines how many bricks fit per square foot by dividing 144 square inches by the area of one brick plus its mortar joint. A standard modular brick (8 × 2.25 inches) with 3/8-inch mortar joints works out to about 6.75 bricks per square foot of wall. One 80-lb bag of mortar mix typically lays about 35–40 standard bricks.",
    faqs: [
      { question: "How many bricks per square foot?", answer: "With standard modular bricks (8 × 2.25 inches) and 3/8-inch mortar joints: approximately 6.75 bricks per square foot for a single-wythe wall (one brick thick)." },
      { question: "How many bricks in a pallet?", answer: "A standard pallet holds about 500 bricks. Weight is approximately 2,000–2,500 lbs per pallet. Always order full pallets when possible — per-brick prices are significantly lower." },
      { question: "How much mortar do I need?", answer: "One 80-lb bag of mortar mix lays approximately 35–40 standard bricks. For every 100 square feet of wall, you'll need roughly 17–20 bags of mortar." },
    ],
    relatedSlugs: ["concrete-calculator", "paver-calculator", "retaining-wall-calculator", "sand-calculator"],
    category: "concrete-masonry",
  },
  {
    slug: "sod-calculator",
    title: "Sod Calculator",
    shortTitle: "Sod",
    description: "Calculate how many rolls or pallets of sod you need for your lawn.",
    metaDescription: "Free sod calculator — estimate rolls, pallets, and cost for new lawn installation. Enter your lawn dimensions for instant results.",
    intro: "Installing sod gives you an instant lawn, but ordering the right amount is key. This calculator estimates rolls, pallets, and cost based on your lawn area.",
    fields: [
      { name: "length", label: "Lawn Length", unit: "feet", placeholder: "50" },
      { name: "width", label: "Lawn Width", unit: "feet", placeholder: "30" },
      { name: "wastePercent", label: "Waste Factor", unit: "%", placeholder: "5", defaultValue: 5 },
      { name: "pricePerSqFt", label: "Price per Sq Ft (optional)", unit: "$", placeholder: "0.45", defaultValue: 0.45 },
    ],
    results: [
      { label: "Total Area", unit: "sq ft", key: "totalArea" },
      { label: "Sod Needed (with waste)", unit: "sq ft", key: "sodNeeded" },
      { label: "Rolls (10 sq ft each)", unit: "rolls", key: "rolls" },
      { label: "Pallets (450 sq ft each)", unit: "pallets", key: "pallets" },
      { label: "Estimated Cost", unit: "$", key: "cost" },
    ],
    formula: "Total area = Length × Width. Sod needed = Area × (1 + waste%). Rolls = Sod needed ÷ 10. Pallets = Sod needed ÷ 450.",
    howToUse: [
      "Measure your lawn area in feet.",
      "Add 5% waste for rectangular areas, 10% for irregular shapes.",
      "Enter local sod price per square foot if known.",
      "Review rolls and pallet estimates.",
    ],
    howItWorks: "A standard sod roll is 2 feet × 5 feet (10 square feet). A full pallet contains about 45 rolls (450 square feet), though this varies by supplier. The calculator adds your waste factor for trimming around edges, curves, and obstacles. Sod is perishable — install it within 24 hours of delivery.",
    faqs: [
      { question: "How much does sod cost?", answer: "Sod typically costs $0.30–$0.80 per square foot, or $130–$360 per pallet (450 sq ft). Delivery fees range from $50–$150. Total installed cost including soil prep is usually $1–$2 per square foot." },
      { question: "How much sod is on a pallet?", answer: "A standard pallet has about 450 square feet (45 rolls at 10 sq ft each). Some suppliers use 500 sq ft pallets. Always confirm with your supplier. A pallet weighs 2,000–3,000 lbs." },
      { question: "When is the best time to lay sod?", answer: "Early fall is ideal — cooler temperatures with warm soil promote root growth. Spring is second best. Avoid peak summer heat. Sod can be laid year-round in mild climates but avoid frozen ground." },
    ],
    relatedSlugs: ["mulch-calculator", "topsoil-calculator", "sand-calculator"],
    category: "landscaping",
  },
  {
    slug: "insulation-calculator",
    title: "Insulation Calculator",
    shortTitle: "Insulation",
    description: "Calculate batts or rolls of insulation needed for walls, attics, and floors.",
    metaDescription: "Free insulation calculator — estimate batts, rolls, or blown-in insulation needed for walls, attics, and crawlspaces. Includes R-value guidance.",
    intro: "Proper insulation saves energy and money. This calculator estimates how much batt or roll insulation you need for walls or attic spaces based on stud spacing and area dimensions.",
    fields: [
      { name: "areaLength", label: "Area Length", unit: "feet", placeholder: "40" },
      { name: "areaWidth", label: "Area Width / Height", unit: "feet", placeholder: "8" },
      { name: "studSpacing", label: "Stud Spacing", type: "select", options: [{ label: "16\" on center", value: 16 }, { label: "24\" on center", value: 24 }] },
      { name: "rollCoverage", label: "Coverage per Roll/Bag", unit: "sq ft", placeholder: "40", defaultValue: 40 },
    ],
    results: [
      { label: "Total Area", unit: "sq ft", key: "totalArea" },
      { label: "Cavities", unit: "cavities", key: "cavities" },
      { label: "Rolls/Bags Needed", unit: "", key: "rollsNeeded" },
    ],
    formula: "Total area = Length × Width. Subtract ~6% for studs/framing. Rolls needed = ceil(Insulation area ÷ Roll coverage).",
    howToUse: [
      "Measure the area to insulate (length × height for walls, length × width for attics).",
      "Select your stud spacing.",
      "Enter the coverage per roll or bag from the product label.",
      "Review the quantity needed.",
    ],
    howItWorks: "This calculator computes the total area, subtracts approximately 6% for framing members (studs, plates, headers), and divides by the coverage per roll or bag. The actual framing percentage varies — walls with many windows or doors have more framing. For attic blown-in insulation, the 'coverage per bag' depends on the desired R-value and depth — check the manufacturer's coverage chart on the bag.",
    faqs: [
      { question: "What R-value do I need?", answer: "Climate-dependent. Zone 1–2 (Southern US): R-13 walls, R-30 attic. Zone 3–4: R-13 to R-15 walls, R-38 attic. Zone 5–7 (Northern US): R-20+ walls, R-49 to R-60 attic. Check the DOE recommendations for your zip code." },
      { question: "Batts vs blown-in insulation?", answer: "Batts are easier to DIY and better for walls. Blown-in is better for attics (fills irregular spaces and covers existing insulation). Blown-in typically requires renting a blower machine ($50–$100/day, often free with purchase of 10+ bags)." },
      { question: "Should I insulate interior walls?", answer: "Not for energy efficiency — they separate conditioned spaces. But insulate interior walls for sound dampening between bedrooms and bathrooms, or between living areas and home offices." },
    ],
    relatedSlugs: ["drywall-calculator", "lumber-calculator", "roofing-calculator"],
    category: "interior",
  },
  {
    slug: "retaining-wall-calculator",
    title: "Retaining Wall Calculator",
    shortTitle: "Retaining Wall",
    description: "Calculate blocks, gravel, and materials for a retaining wall.",
    metaDescription: "Free retaining wall calculator — estimate blocks, base material, and cap stones needed. Enter wall dimensions for instant results.",
    intro: "A retaining wall holds back soil and prevents erosion. This calculator estimates the number of retaining wall blocks, base gravel, and cap stones for your project.",
    fields: [
      { name: "wallLength", label: "Wall Length", unit: "feet", placeholder: "20" },
      { name: "wallHeight", label: "Wall Height", unit: "feet", placeholder: "3" },
      { name: "blockLength", label: "Block Length (face)", unit: "inches", placeholder: "12", defaultValue: 12 },
      { name: "blockHeight", label: "Block Height", unit: "inches", placeholder: "4", defaultValue: 4 },
    ],
    results: [
      { label: "Wall Area", unit: "sq ft", key: "wallArea" },
      { label: "Blocks Needed (+5%)", unit: "blocks", key: "blocksNeeded" },
      { label: "Rows", unit: "rows", key: "rows" },
      { label: "Cap Stones", unit: "caps", key: "capStones" },
      { label: "Base Gravel", unit: "cubic yards", key: "baseGravel" },
    ],
    formula: "Rows = Wall Height (in) ÷ Block Height. Blocks per row = Wall Length (in) ÷ Block Length. Total blocks = Rows × Blocks per row × 1.05. Cap stones = Blocks per row. Base gravel: 6 inches deep × 2 feet wide × Wall Length.",
    howToUse: [
      "Enter the total wall length in feet.",
      "Enter the desired finished height in feet.",
      "Enter the block face dimensions (check the product).",
      "Review block count, caps, and base gravel needed.",
    ],
    howItWorks: "This calculator divides wall area into block face area to determine total blocks needed, adds 5% for cuts and waste, and calculates cap stones for the top row. The base gravel estimate assumes a 6-inch deep, 24-inch wide compacted gravel trench — essential for proper drainage and stability. Walls over 4 feet typically require engineering, geogrid reinforcement, and possibly a permit.",
    faqs: [
      { question: "How high can I build a retaining wall without a permit?", answer: "Most jurisdictions allow retaining walls up to 4 feet without a permit or engineering. Walls over 4 feet typically require a building permit and may need an engineer's design. Check local codes." },
      { question: "Do I need drainage behind a retaining wall?", answer: "Yes, always. Backfill with 12 inches of gravel behind the wall and install a perforated drain pipe at the base. Without drainage, water pressure builds up behind the wall and causes failure." },
      { question: "What base do I need for a retaining wall?", answer: "Dig a trench 6–8 inches deep and 24 inches wide. Fill with compacted gravel (crusher run works well). The first course of blocks should be partially buried below grade for stability." },
    ],
    relatedSlugs: ["gravel-calculator", "paver-calculator", "concrete-calculator", "sand-calculator"],
    category: "concrete-masonry",
  },
  {
    slug: "paver-calculator",
    title: "Paver Calculator",
    shortTitle: "Pavers",
    description: "Calculate how many pavers you need for patios, walkways, and driveways.",
    metaDescription: "Free paver calculator — estimate pavers needed, sand base, and gravel for patios, walkways, and driveways. Enter dimensions for instant results.",
    intro: "Pavers create beautiful patios, walkways, and driveways. This calculator estimates the number of pavers, base material, and bedding sand for your project.",
    fields: [
      { name: "areaLength", label: "Area Length", unit: "feet", placeholder: "15" },
      { name: "areaWidth", label: "Area Width", unit: "feet", placeholder: "10" },
      { name: "paverLength", label: "Paver Length", unit: "inches", placeholder: "8", defaultValue: 8 },
      { name: "paverWidth", label: "Paver Width", unit: "inches", placeholder: "4", defaultValue: 4 },
      { name: "wastePercent", label: "Waste Factor", unit: "%", placeholder: "10", defaultValue: 10 },
    ],
    results: [
      { label: "Total Area", unit: "sq ft", key: "totalArea" },
      { label: "Pavers Needed", unit: "pavers", key: "paversNeeded" },
      { label: "Base Gravel (4\" deep)", unit: "cubic yards", key: "gravelNeeded" },
      { label: "Bedding Sand (1\" deep)", unit: "cubic yards", key: "sandNeeded" },
    ],
    formula: "Paver area = (Paver Length × Paver Width) ÷ 144 sq ft. Pavers needed = (Total area ÷ Paver area) × (1 + waste%). Base gravel = Area × 4/12 ÷ 27. Sand = Area × 1/12 ÷ 27.",
    howToUse: [
      "Measure the area to be paved in feet.",
      "Enter your paver dimensions in inches.",
      "Adjust waste factor — 10% for running bond, 15% for herringbone.",
      "Review pavers, gravel, and sand estimates.",
    ],
    howItWorks: "This calculator divides your project area by the face area of a single paver to determine quantity, adding waste for cuts and breakage. It also estimates the base gravel (4 inches compacted is standard) and bedding sand (1 inch) needed under the pavers. For driveways, increase the gravel base to 6–8 inches.",
    faqs: [
      { question: "How many pavers per square foot?", answer: "It depends on paver size. 4×8 inch pavers: about 4.5 per sq ft. 6×6 inch: about 4 per sq ft. 6×9 inch: about 2.67 per sq ft. 12×12 inch: 1 per sq ft." },
      { question: "What goes under pavers?", answer: "From bottom to top: compacted soil, 4–6 inches of compacted gravel base (crusher run), 1 inch of bedding sand (leveled with a screed), then pavers, then polymeric sand swept into the joints." },
      { question: "How much does a paver patio cost?", answer: "DIY material cost runs $3–$6 per square foot for concrete pavers and base materials. Professional installation is typically $10–$25 per square foot depending on the paver type and pattern complexity." },
    ],
    relatedSlugs: ["gravel-calculator", "sand-calculator", "concrete-calculator", "brick-calculator"],
    category: "concrete-masonry",
  },
  {
    slug: "rebar-calculator",
    title: "Rebar Calculator",
    shortTitle: "Rebar",
    description: "Calculate rebar quantity, spacing, and weight for concrete slabs and footings.",
    metaDescription: "Free rebar calculator — estimate rebar pieces, total length, and weight for concrete slabs and footings. Enter slab dimensions and spacing for instant results.",
    intro: "Rebar reinforces concrete and prevents cracking. This calculator estimates the number of rebar pieces needed for a grid layout in concrete slabs or footings.",
    fields: [
      { name: "slabLength", label: "Slab Length", unit: "feet", placeholder: "20" },
      { name: "slabWidth", label: "Slab Width", unit: "feet", placeholder: "20" },
      { name: "spacing", label: "Rebar Spacing", unit: "inches", placeholder: "12", defaultValue: 12 },
      { name: "rebarSize", label: "Rebar Size", type: "select", options: [{ label: "#3 (3/8\")", value: 0.376 }, { label: "#4 (1/2\")", value: 0.668 }, { label: "#5 (5/8\")", value: 1.043 }] },
    ],
    results: [
      { label: "Lengthwise Bars", unit: "bars", key: "lengthBars" },
      { label: "Widthwise Bars", unit: "bars", key: "widthBars" },
      { label: "Total Bars", unit: "bars", key: "totalBars" },
      { label: "Total Rebar Length", unit: "linear feet", key: "totalLength" },
      { label: "Estimated Weight", unit: "lbs", key: "totalWeight" },
    ],
    formula: "Lengthwise bars = floor(Width × 12 ÷ Spacing) + 1. Widthwise bars = floor(Length × 12 ÷ Spacing) + 1. Total length = (Lengthwise × Length) + (Widthwise × Width). Weight = Total length × weight per foot for chosen size.",
    howToUse: [
      "Enter slab length and width in feet.",
      "Enter the desired rebar spacing (12 inches is common for residential slabs).",
      "Select the rebar size (#3 or #4 is typical for slabs).",
      "Review the quantity and weight estimates.",
    ],
    howItWorks: "Rebar is laid in a grid pattern inside the concrete. This calculator determines how many bars run in each direction based on your spacing, then calculates total linear feet and weight. Standard practice is to place rebar at the center of the slab thickness, supported on rebar chairs. Bars should overlap by at least 40 bar diameters at splices (20 inches for #4 rebar).",
    faqs: [
      { question: "What size rebar for a concrete slab?", answer: "#3 (3/8\") or #4 (1/2\") rebar is standard for residential slabs like driveways and patios. #5 (5/8\") is used for structural footings, grade beams, and walls. Spacing is typically 12–18 inches on center." },
      { question: "Do I need rebar in a 4-inch slab?", answer: "For walkways and patios, wire mesh or fiber reinforcement is often sufficient. For driveways, garages, and any slab carrying loads, rebar is recommended. Some codes require it. When in doubt, use rebar — the cost is minimal compared to replacing a cracked slab." },
      { question: "How much does rebar cost?", answer: "#3 rebar costs about $0.15–$0.30 per linear foot. #4 runs $0.25–$0.50 per foot. A 20-foot stick of #4 rebar costs about $5–$10. Rebar chairs (supports) cost about $0.25–$0.50 each." },
    ],
    relatedSlugs: ["concrete-calculator", "retaining-wall-calculator", "stair-calculator"],
    category: "concrete-masonry",
  },
  {
    slug: "topsoil-calculator",
    title: "Topsoil Calculator",
    shortTitle: "Topsoil",
    description: "Calculate how much topsoil you need in cubic yards and tons.",
    metaDescription: "Free topsoil calculator — estimate cubic yards, tons, and cost for garden beds, lawn prep, and grading. Enter dimensions for instant results.",
    intro: "Whether you're starting a new lawn, filling raised beds, or grading your yard, this calculator estimates how much topsoil to order.",
    fields: [
      { name: "length", label: "Length", unit: "feet", placeholder: "30" },
      { name: "width", label: "Width", unit: "feet", placeholder: "20" },
      { name: "depth", label: "Depth", unit: "inches", placeholder: "4" },
      { name: "pricePerYard", label: "Price per Cubic Yard (optional)", unit: "$", placeholder: "30", defaultValue: 30 },
    ],
    results: [
      { label: "Volume", unit: "cubic yards", key: "cubicYards" },
      { label: "Volume", unit: "cubic feet", key: "cubicFeet" },
      { label: "Weight (approx)", unit: "tons", key: "tons" },
      { label: "Estimated Cost", unit: "$", key: "cost" },
    ],
    formula: "Volume (cu ft) = Length × Width × Depth(in)/12. Cubic yards = Volume ÷ 27. Topsoil weighs ~2,200 lbs (1.1 tons) per cubic yard.",
    howToUse: [
      "Measure the area length and width in feet.",
      "Determine depth needed — 4–6 inches for new lawns, 8–12 inches for garden beds.",
      "Enter values and review results.",
      "Enter price per yard for cost estimate.",
    ],
    howItWorks: "This calculator computes volume from your dimensions. Topsoil is lighter than sand or gravel, averaging about 2,200 lbs per cubic yard (varies by moisture content). For new lawns, spread 4–6 inches of topsoil over compacted subgrade. For garden beds and raised planters, use 8–12 inches. Topsoil settles 10–15% after watering, so order accordingly.",
    faqs: [
      { question: "How much topsoil do I need for a new lawn?", answer: "Spread 4–6 inches of topsoil over the area. For a 1,000 sq ft lawn at 4 inches deep, you need about 12.3 cubic yards (roughly 13.5 tons). Topsoil settles, so 6 inches is better if budget allows." },
      { question: "What is the difference between topsoil and garden soil?", answer: "Topsoil is the top layer of natural soil, screened for debris. Garden soil is topsoil blended with compost and amendments for better drainage and nutrients. Use topsoil for grading and lawn prep; garden soil for planting beds." },
      { question: "How much does topsoil cost?", answer: "Bulk topsoil costs $15–$50 per cubic yard depending on quality and location, plus delivery ($50–$150). Bagged topsoil from hardware stores costs significantly more per cubic yard." },
    ],
    relatedSlugs: ["mulch-calculator", "sod-calculator", "sand-calculator", "gravel-calculator"],
    category: "landscaping",
  },
];

export function getCalculatorBySlug(slug: string): CalculatorConfig | undefined {
  return calculators.find((c) => c.slug === slug);
}

export function getRelatedCalculators(slugs: string[]): CalculatorConfig[] {
  return slugs.map((s) => calculators.find((c) => c.slug === s)).filter(Boolean) as CalculatorConfig[];
}
